modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"
license = "Custom"

[[mods]]
modId = "beachparty"
version = "${version}"
displayName = "[Let's Do] Beachparty"
displayURL = "https://github.com/satisfyu/Beachparty"
authors = "Satisfy, Jason13"
credits = "MissLilitu, Cristelknight, BaumeisterJo"
textures= "Satisfy, Iri, Dev_Myst"
description = '''
Take a break - build sandcastles, drink cocktails and enjoy your Minecraft Session.
'''
logoFile = "pack.png"

[[dependencies.beachparty]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beachparty]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beachparty]]
